### ISSUE TITLE
 cannot import name dataclass_transform

### ISSUE THREAD

**Issue by kidcad1412** [doccano/doccano-client#117]
python=3.8.8

```bash
pip install doccano-client
```

but when I import it:

```python
from doccano_client import DoccanoClient
```

```bash
Traceback (most recent call last):
  File "D:\software\ANACONA\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-45fa2064b15e>", line 1, in <module>
    from doccano_client import DoccanoClient
  File "D:\software\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\software\ANACONA\lib\site-packages\doccano_client\__init__.py", line 1, in <module>
    from doccano_client.client import DoccanoClient
  File "D:\software\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\software\ANACONA\lib\site-packages\doccano_client\client.py", line 6, in <module>
    from doccano_client.models.comment import Comment
  File "D:\software\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\software\ANACONA\lib\site-packages\doccano_client\models\comment.py", line 3, in <module>
    from pydantic import BaseModel
  File "D:\software\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 52, in init pydantic.dataclasses
ImportError: cannot import name dataclass_transform
```

**Comment by Hironsan** [comment]
Can you import the following?

```python
from typing_extensions import dataclass_transform
```

**Comment by kidcad1412** [comment]
thanks，Pydantic=1.10.2 will raise this error，Pydantic=1.9.2 is ok
