### ISSUE TITLE
`list_project()` error

### ISSUE THREAD

**Issue by wonyoungseo** [doccano/doccano-client#144]
How to reproduce the behaviour
---------

I'm just trying out doccano-client to integrate Doccano with our system. 

According to the documentation`list_project()` method returns generator `Iterator[Project]`, I encountered TypeError when trying to yield project.

```python
# test.py

from doccano_client import DoccanoClient

# instantiate a client and log in to a Doccano instance
client = DoccanoClient(MY_HOST)
client.login(username=ADMIN_USERNAME, password=ADMIN_PW)

if __name__ == "__main__":
    # get basic information about the authorized user
    user = client.get_profile()
    print(user)

    # # list all projects
    projects = client.list_projects()
    print([p for p in projects])
```
```
# printed result
$ python test.py
id=2 username='admin' is_superuser=True is_staff=True
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print([p for p in projects])
  File "test.py", line 18, in <listcomp>
    print([p for p in projects])
  File "/Users/wg/.pyenv/versions/3.8.2/lib/python3.8/site-packages/doccano_client/client.py", line 289, in list_projects
    yield from self.project.list()
  File "/Users/wg/.pyenv/versions/3.8.2/lib/python3.8/site-packages/doccano_client/usecase/project.py", line 40, in list
    yield from self._repository.list()
  File "/Users/wg/.pyenv/versions/3.8.2/lib/python3.8/site-packages/doccano_client/repositories/project.py", line 37, in list
    for project in projects["results"]:
TypeError: list indices must be integers or slices, not str
```

Your Environment
---------

*   Operating System: MacOS
*   Python Version: 3.8.2
*   Package Version: 1.2.7

**Comment by Hironsan** [comment]
Please access `MY_HOST/v1/projects` in your browser and tell me what you get as a response.

**Comment by wonyoungseo** [comment]
@Hironsan 

I get a list of dictionary like this 
```
HTTP 200 OK
Allow: GET, POST, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "id": 2,
        "name": "PROJECT NAME",
        "description": "SOME DESCRIPTION",
        "guideline": "SOME GUIDELINE",
        "users": [
            2,
            4,
            5,
            6,
            8,
            9,
            10
        ],
        "current_users_role": {
            "is_project_admin": true,
            "is_annotator": false,
            "is_annotation_approver": false
        },
        "project_type": "DocumentClassification",
        "updated_at": "DATE",
        "random_order": true,
        "collaborative_annotation": true,
        "single_class_classification": true,
        "tags": [],
        "resourcetype": "TextClassificationProject"
    },
...
]

**Comment by Hironsan** [comment]
It seems that your doccano version is older. The response is changed in https://github.com/doccano/doccano/pull/1668. 

One way is to downgrade `doccan-client`.

```bash
$ pip install doccano-client==1.1.1
$ python
>>> from doccano_client import DoccanoClient
>>> client = DoccanoClient(MY_HOST, ADMIN_USERNAME, ADMIN_PW)
>>> client.get_project_list()
```
