### ISSUE TITLE
Calling list_examples triggers HTTP 500 errors after every 5 examples

### ISSUE THREAD

**Issue by cuihaoleo** [doccano/doccano-client#146]
How to reproduce the behaviour
---------

I'm importing examples among which some were verified externally. So I wrote a simple script to set examples with a particular metadata value as verified:

```python3
import argparse
from doccano_client import DoccanoClient

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("url", help="Doccano URL")
    parser.add_argument("project_id", help="Project ID")
    parser.add_argument("-U", "--username", required=True, help="Username")
    parser.add_argument("-P", "--password", required=True, help="Password")
    args = parser.parse_args()

    client = DoccanoClient(args.url)
    client.login(username=args.username, password=args.password)

    for example in client.list_examples(args.project_id, False):
        if example.meta.get('verified'):
            client.update_example_state(args.project_id, example.id)
            print(f"Set #{example.id} to done")
        else:
            break

if __name__ == "__main__":
    main()
```

The loop dies after every 5 examples:
```
Set #76591 to done
Set #76592 to done
Set #76593 to done
Set #76594 to done
Set #76595 to done
Traceback (most recent call last):
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 24, in verbose_raise_for_status
    response.raise_for_status()
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.1.1:3000/v1/http://127.0.1.1/v1/projects/6/examples?confirmed=False&limit=5&offset=5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/cuih7/poligraph-revision/poligraph/custom_ner_training/approve_verified_doccano_examples.py", line 27, in <module>
    main()
  File "/data/cuih7/poligraph-revision/poligraph/custom_ner_training/approve_verified_doccano_examples.py", line 18, in main
    for example in client.list_examples(args.project_id, False):
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/client.py", line 589, in list_examples
    yield from self.example.list(project_id, is_confirmed)
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/usecase/example.py", line 44, in list
    yield from self._repository.list(project_id, is_confirmed)
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/repositories/example.py", line 63, in list
    response = self._client.get(examples["next"])
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 109, in get
    verbose_raise_for_status(response)
  File "/data/cuih7/miniconda3/envs/nlp20230222/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 26, in verbose_raise_for_status
    raise DoccanoAPIError(str(err), err.response)
doccano_client.exceptions.DoccanoAPIError: 500 Server Error: Internal Server Error for url: http://127.0.1.1:3000/v1/http://127.0.1.1/v1/projects/6/examples?confirmed=False&limit=5&offset=5
```

And this is the error seen from the server side:

```
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/auth/login/ HTTP/1.1" 200 50 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "GET /v1/projects/6/examples?confirmed=False HTTP/1.1" 200 3632 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/projects/6/examples/76591/states HTTP/1.1" 201 88 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/projects/6/examples/76592/states HTTP/1.1" 201 88 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/projects/6/examples/76593/states HTTP/1.1" 201 88 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/projects/6/examples/76594/states HTTP/1.1" 201 88 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "POST /v1/projects/6/examples/76595/states HTTP/1.1" 201 88 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
backend_1   | [2023-03-24 16:55:39 +0000] [273] [ERROR] [django.request::log_response::241] Internal Server Error: /v1/http:/127.0.1.1/v1/projects/6/examples
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
backend_1   |     response = get_response(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
backend_1   |     response = response.render()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 114, in render
backend_1   |     self.content = self.rendered_content
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 90, in rendered_content
backend_1   |     template = self.resolve_template(self.template_name)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 72, in resolve_template
backend_1   |     return select_template(template, using=self.using)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
backend_1   |     raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
backend_1   | django.template.exceptions.TemplateDoesNotExist: index.html
backend_1   | [2023-03-24 16:55:39 +0000] [273] [ERROR] [django.request::log_response::241] Internal Server Error: /v1/http:/127.0.1.1/v1/projects/6/examples
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
backend_1   |     response = get_response(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
backend_1   |     response = response.render()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 114, in render
backend_1   |     self.content = self.rendered_content
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 90, in rendered_content
backend_1   |     template = self.resolve_template(self.template_name)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 72, in resolve_template
backend_1   |     return select_template(template, using=self.using)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
backend_1   |     raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
backend_1   | django.template.exceptions.TemplateDoesNotExist: index.html
nginx_1     | 172.19.0.1 - - [24/Mar/2023:16:55:39 +0000] "GET /v1/http://127.0.1.1/v1/projects/6/examples?confirmed=False&limit=5&offset=5 HTTP/1.1" 500 145 "http://127.0.1.1:3000/" "python-requests/2.28.1" "-"
```

Your Environment
---------

*   Operating System: Debian 11
*   Python Version: 3.10.9 (client side)
*   Package Version: `doccano-client==1.2.7`

Doccano is deployed through docker using the default `docker-compose.prod.yml`

**Comment by daleevans** [comment]
The easiest fix is probably to put this behind an reverse proxy and access it via a regular hostname without a special port, eg. https://mysubdomain.host.com .  This is just a consequence of how DRF constructs the 'next' host keys.

**Comment by adbelniak** [comment]
Hi, I have the same problem. IMO reverse proxy i quite complicated. Is there any solution or fix ?

**Comment by creisle** [comment]
I had this issue where it dups the api_base_url part of the request url too but for a different reason. The dup above is probably related to the port difference

```
http://127.0.1.1:3000/v1/http://127.0.1.1/v1/projects/6/examples?confirmed=False&limit=5&offset=5
```

My base_url was https but for some reason list_projects was changing it to http so then this line was casuing the problem https://github.com/doccano/doccano-client/blob/master/doccano_client/repositories/base.py#L105. I changed that line to use this function ignore http vs https and it fixed my issue.

```python
def strip_base_url(base_url, url):
    stripped_base_url = re.sub(r'^https?', '', base_url)
    stripped_url = re.sub(r'^https?', '', url)
    if stripped_url.startswith(stripped_base_url):
        return stripped_url[len(stripped_base_url) + 1:]
    return url
```

 It would be trivial to have it also ignore port. There is probably a more elegant less hacky fix if we trace that url back further but this worked for me in the meantime.
