### ISSUE TITLE
Unable to retrieve projects with tags

### ISSUE THREAD

**Issue by dsciacca** [doccano/doccano-client#149]
How to reproduce the behaviour
---------

I'm unable to retrieve any projects that have tags associated using `doccano-client`. To reproduce:
1. create a Doccano project
2. Select the project in the Doccano UI and go to Settings via the lefthand menu
3. add any number of tags 
4. Take note of the project's ID in the project's URL
5. Execute the following code
```python
from doccano_client import DoccanoClient


# Replace below w/ your details
host = "https://doccano.instance.url"
user = "username"
pswd = "password"
project_id = 1


client = DoccanoClient(host)
client.login(user, pswd)

# Getting by ID produces error
client.find_project_by_id(project_id)

# Getting all projects also produces error
list(client.list_projects())
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-56bd588657fc>", line 1, in <module>
    for project in projects:
  File "/usr/local/lib/python3.9/site-packages/doccano_client/client.py", line 289, in list_projects
    yield from self.project.list()
  File "/usr/local/lib/python3.9/site-packages/doccano_client/usecase/project.py", line 40, in list
    yield from self._repository.list()
  File "/usr/local/lib/python3.9/site-packages/doccano_client/repositories/project.py", line 38, in list
    yield Project.parse_obj(project)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Project
tags -> 0
  str type expected (type=type_error.str)
```

Your Environment
---------

*   Operating System: macOS Ventura 13.3.1
*   Python Version: 3.9.6
*   Package Version: 1.2.7

**Comment by dsciacca** [comment]
Quick update - upon digging I believe I've found the core issue. The [Project class](https://github.com/doccano/doccano-client/blob/master/doccano_client/models/project.py#L38) lists the `tags` property type as a `List[str]` but the response JSON retrieved from the API call made under the hood has the value of the `tags` key as a list of dicts with str keys and values that are either int or str, for example:
```
[{'id': 4, 'project': 1, 'text': 'test1'},
  {'id': 5, 'project': 1, 'text': 'test2'},
  {'id': 6, 'project': 1, 'text': 'test3'}]
```
This causes an issue during the call to `Project.parse_obj()` happening in both `ProjectRepository.list()` and `ProjectRepository.find_by_id()` methods. If the `tags` key in the response JSON is updated to just a list of values extracted from the `text` field of the `tags` list of dicts (e.g. `project_json['tags'] = [tag.get("text") for tag in project_json.get("tags")]`), then the `Project.parse_obj()` call is able to succeed without error. I'm happy to put in a PR for this change if desired, but am unsure if this would be adequate or if a change to the API itself to return `tags` in the expected format would be more desirable - let me know. Thanks!

**Comment by dsciacca** [comment]
Update: the `create_project()` method is also impacted and I'm unable to create a project with tags. [Documentation](https://doccano.github.io/doccano-client/usage/#doccano_client.client.DoccanoClient.create_project) states tags should be `List[str]` but attempting to create a project this way returns an error. To reproduce:
```python
from doccano_client import DoccanoClient


# Replace below w/ your details
host = "https://doccano.instance.url"
user = "username"
pswd = "password"
project_id = 1


client = DoccanoClient(host)
client.login(user, pswd)

client.create_project("test create with tags", project_type="ImageClassification", description="test create project with tags", tags=["testTag1", "testTag2"])
```
This results in the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/doccano_client/repositories/base.py", line 24, in verbose_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://doccano.instance.url/v1/projects
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-39-3f970c629f42>", line 1, in <module>
    client.create_project("test create with tags", project_type="ImageClassification", description="test create project with tags", tags=["testTag1", "testTag2"])
  File "/usr/local/lib/python3.9/site-packages/doccano_client/client.py", line 383, in create_project
    return self.project.create(
  File "/usr/local/lib/python3.9/site-packages/doccano_client/usecase/project.py", line 87, in create
    return self._repository.create(project)
  File "/usr/local/lib/python3.9/site-packages/doccano_client/repositories/project.py", line 54, in create
    response = self._client.post("projects", json=project.dict(exclude={"id"}))
  File "/usr/local/lib/python3.9/site-packages/doccano_client/repositories/base.py", line 124, in post
    verbose_raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/doccano_client/repositories/base.py", line 26, in verbose_raise_for_status
    raise DoccanoAPIError(str(err), err.response)
doccano_client.exceptions.DoccanoAPIError: {'tags': [{'non_field_errors': ['Invalid data. Expected a dictionary, but got str.']}, {'non_field_errors': ['Invalid data. Expected a dictionary, but got str.']}]}
```
This error response suggests that the create API is expecting a `List[Dict[str, Any]` like is returned by the API rather than `List[str]` as documentation and the properties of the `Project` class suggest. Running w/ this assumption, I tried creating this time w/ `tags` as `List[Dict[str, Any]`:
```python
client.create_project("test create with tags", project_type="ImageClassification", description="test create project with tags", tags=[{"text": "testTag1"}, {"text": "testTag2"}])
```
but this brings us back to the same `pydantic.error_wrappers.ValidationError`, this time caused by `ProjectUseCase.create()` due to the attempt to pass the `List[Dict[str, Any]]` type in for `tags` in the `Project` constructor, which expects `List[str]`, and this happens before the API call is actually made. Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-52ed3f58c976>", line 1, in <module>
    client.create_project("test create with tags", project_type="ImageClassification", description="test create project with tags", tags=[{"text": "testTag1"}, {"text": "testTag2"}])
  File "/usr/local/lib/python3.9/site-packages/doccano_client/client.py", line 383, in create_project
    return self.project.create(
  File "/usr/local/lib/python3.9/site-packages/doccano_client/usecase/project.py", line 74, in create
    project = Project(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Project
tags -> 0
  str type expected (type=type_error.str)
tags -> 1
  str type expected (type=type_error.str)
```
I've confirmed passing a `List[Dict[str, Any]]` would work at the API level by doing the following:
```python
import requests

# Replace below w/ your details
host = "https://doccano.instance.url"
user = "username"
pswd = "password"

# setting session as in BaseRepository (https://github.com/doccano/doccano-client/blob/master/doccano_client/repositories/base.py#L30)
host = host.rstrip("/")
_session = requests.Session()
headers = {
    "content-type": "application/json",
    "accept": "application/json",
    "referer": host,
}
_session.headers.update(headers)
api_url = host + "/v1"
_session.verify = True
# authenticate
_session.post(api_url + "/auth/login/", json={"username": user, "password": pswd})
_session.headers.update({"X-CSRFToken": _session.cookies.get("csrftoken")})

project_properties = {
    "name": "test create with tags", 
    "project_type": "ImageClassification", 
    "description": "test create project with tags", 
    "tags": [{"text": "testTag1"}, {"text": "testTag2"}],  # List[Dict[str, str]]
    'resourcetype': 'ImageClassificationProject'
}
c_api_resp = _session.post(api_url + "/projects", json=project_properties)
```
This works and the project is created as expected, confirming that the issue is a disconnect between what the API expects/returns and the class definition of a `Project` in the `doccano-client`

**Comment by Hironsan** [comment]
Thank you for your detailed analysis.
