### ISSUE TITLE
Uploading the file from the API fails

### ISSUE THREAD

**Issue by ChiLynn123** [doccano/doccano-client#16]
Hello, I made an error uploading the document using the API, but the document can appear in the Doccano instance database. Looking forward to your reply to my questions, thank you very much!

r_du = doccano_client.post_doc_upload(8, "json", "fail1.json", "D:\WPSCloud")

error:
Traceback (most recent call last): File "D:/doccano/doccano-client/doccano_api_client/example.py", line 113, in <module> r_du = doccano_client.post_doc_upload(8, "csv", "data_xa.csv", "D:\WPSCloud") File "D:\doccano\doccano-client\doccano_api_client\__init__.py", line 521, in post_doc_upload data=data File "D:\doccano\doccano-client\doccano_api_client\__init__.py", line 64, in post request_url, data=data, files=files, json=json).json() File "E:\Anaconda\lib\site-packages\requests\models.py", line 885, in json return complexjson.loads(self.text, **kwargs) File "E:\Anaconda\lib\json\__init__.py", line 354, in loads return _default_decoder.decode(s) File "E:\Anaconda\lib\json\decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "E:\Anaconda\lib\json\decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by SwannChelly** [comment]
Hi, 

I have a similar issu when trying to upload a txt file using : 

`doccano_client.post_doc_upload(1,'txt','input_1.txt','./')`

And it returns : 

`simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)`

Any update about this bug ? 

Best regards,

**Comment by EnzoNclt** [comment]
Hi, i also have a similar issue while using `post_doc_upload()`, the file is correctly uploaded but it seems to crash when i try to injest it.

Following the error raised by `doccano task`:

```
[2021-06-22 13:59:58,940: INFO/MainProcess] Task api.tasks.injest_data[14eabc0b-c104-40e8-ac23-3f068f872e8b] received
[2021-06-22 13:59:58,946: ERROR/ForkPoolWorker-2] Task api.tasks.injest_data[14eabc0b-c104-40e8-ac23-3f068f872e8b] raised unexpected: Http404('No Project matches the given query.')
Traceback (most recent call last):
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
api.models.Project.DoesNotExist: Project matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/backend/api/tasks.py", line 90, in injest_data
    project = get_object_or_404(Project, pk=project_id)
  File "/Users/enzo/Workspace/Testing/doccano-ft/dft_env/lib/python3.9/site-packages/django/shortcuts.py", line 78, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Project matches the given query.
```

**Comment by cliuxinxin** [comment]
Hi, same issue here

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doccano_api_client/__init__.py in post_doc_upload(self, project_id, file_name, file_path, column_data, column_label, delimiter, encoding, format)
    678             delimiter=delimiter,
    679             encoding=encoding,
--> 680             format=format,
    681         )
    682 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doccano_api_client/__init__.py in post_doc_upload_binary(self, project_id, files, column_data, column_label, delimiter, encoding, format)
    643             "uploadIds": upload_ids,
    644         }
--> 645         return self.post(f"v1/projects/{project_id}/upload", json=upload_data)
...
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[news_test.json.zip](https://github.com/doccano/doccano-client/files/9116838/news_test.json.zip)
