### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by dimidloc** [doccano/doccano-client#45]
How to reproduce the behaviour
---------
`doccano_client.get_doc_download(4,  'json')`

```
backend_1   | Internal Server Error: /v1/projects/4/docs/download
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
backend_1   |     response = get_response(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
backend_1   |     response = response.render()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
backend_1   |     self.content = self.rendered_content
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
backend_1   |     template = self.resolve_template(self.template_name)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
backend_1   |     return select_template(template, using=self.using)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
backend_1   |     raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
backend_1   | django.template.exceptions.TemplateDoesNotExist: index.html
backend_1   | [01/Aug/2021 12:22:12] "GET /v1/projects/4/docs/download?q=json&onlyApproved=false HTTP/1.1" 500 19489
```

Your Environment
---------

*   Operating System: ubuntu
*   Python Version: 3.8
*   Package Version: 1.0.3.dev29+gbb4c9ba (installed from github)

**Comment by azimulislma266** [comment]
thank you

**Comment by Hironsan** [comment]
fixed https://github.com/doccano/doccano-client/pull/59
