### ISSUE TITLE
Typo in commit 170c, should be `requests`

### ISSUE THREAD

**Issue by travishsu** [doccano/doccano-client#76]
How to reproduce the behaviour
---------

Install package from source code
```bash
git clone https://github.com/doccano/doccano-client.git
pip install -e doccano-client
```
Import in python
```python
from doccano_api_client import Doccano
```
I got
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/howayi/workspace/github/doccano/doccano-client/doccano_api_client/__init__.py", line 148, in <module>
    class DoccanoClient(_Router):
  File "/Users/howayi/workspace/github/doccano/doccano-client/doccano_api_client/__init__.py", line 604, in DoccanoClient
    def get_category_type_list(self, project_id: int) -> request.models.Response:
NameError: name 'request' is not defined
```

Your Environment
---------

*   Operating System:
*   Python Version:
*   Package Version:

**Comment by david-engelmann** [comment]
@travishsu Commit #71 being merged should fix this

**Comment by travishsu** [comment]
thx
